In [4]:
import numpy as np

In [18]:
a = np.array([[1, 6],

              [2, 8],

              [3, 11],

              [3, 10],

              [1, 7]])

In [20]:
mean_a = a.mean(axis=0)

In [24]:
mean_a

array([2. , 8.4])

In [22]:
a_centered = np.subtract(a, mean_a)

In [23]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [30]:
a1 = a_centered[:,0]
a2 = a_centered[:,1]

In [32]:
a_centered_sp = np.dot(a1,a2)

In [33]:
a_centered_sp

8.0

In [35]:
N = a.shape[0]
my_cov = a_centered_sp/(N-1)

In [36]:
my_cov

2.0

In [39]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

### Pandas

In [8]:
import pandas as pd

In [9]:
data = {
    "ID": [1,2,3],
"Авторы": ["Alexey Kotikov", "Ivan Suhojaba", "Anton German"]
}

b = pd.DataFrame(data)

In [10]:
b

ID          Авторы
0   1  Alexey Kotikov
1   2   Ivan Suhojaba
2   3    Anton German

In [11]:
book = {
    "ID": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}

In [12]:
b_1 = pd.DataFrame(book)

In [13]:
b_1

ID            book_title  price
0   1           Отцы и дети    450
1   1                 Рудин    300
2   1     Дворянское гнездо    350
3   2      Толстый и тонкий    500
4   2       Дама с собачкой    450
5   3                 Гроза    370
6   3  Таланты и поклонники    290

In [14]:
price = pd.merge(b_1, b, on="ID", how="inner")

In [15]:
top5 = price.nlargest(5,"price")

In [16]:
autorsstat = price.groupby('Авторы').agg({'price':["min","max","median"]})

In [18]:
price

ID            book_title  price          Авторы
0   1           Отцы и дети    450  Alexey Kotikov
1   1                 Рудин    300  Alexey Kotikov
2   1     Дворянское гнездо    350  Alexey Kotikov
3   2      Толстый и тонкий    500   Ivan Suhojaba
4   2       Дама с собачкой    450   Ivan Suhojaba
5   3                 Гроза    370    Anton German
6   3  Таланты и поклонники    290    Anton German

In [19]:
top5

ID         book_title  price          Авторы
3   2   Толстый и тонкий    500   Ivan Suhojaba
0   1        Отцы и дети    450  Alexey Kotikov
4   2    Дама с собачкой    450   Ivan Suhojaba
5   3              Гроза    370    Anton German
2   1  Дворянское гнездо    350  Alexey Kotikov

In [20]:
autorsstat

price            
                 min  max median
Авторы                          
Alexey Kotikov   300  450    350
Anton German     290  370    330
Ivan Suhojaba    450  500    475